/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.diegomrosa.pila;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int pila_launcher=0x7f020000;
    }
    public static final class id {
        public static final int aboutButton=0x7f060008;
        public static final int addItem=0x7f060009;
        public static final int amountEdit=0x7f060002;
        public static final int expensesListButton=0x7f060007;
        public static final int newExpenseButton=0x7f060006;
        public static final int removeItem=0x7f06000a;
        public static final int saveButton=0x7f060005;
        public static final int tagsEdit=0x7f060004;
        public static final int totalEdit=0x7f060003;
        public static final int valueEdit=0x7f060001;
        public static final int webView=0x7f060000;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int expense=0x7f030001;
        public static final int expenses_list=0x7f030002;
        public static final int main=0x7f030003;
    }
    public static final class menu {
        public static final int expenses_list=0x7f050000;
        public static final int expenses_list_context=0x7f050001;
    }
    public static final class string {
        public static final int aboutButtonText=0x7f040003;
        public static final int aboutLabel=0x7f04000f;
        public static final int appName=0x7f040000;
        public static final int expenseAmountText=0x7f040006;
        public static final int expenseLabel=0x7f040004;
        public static final int expenseSaveButtonText=0x7f040009;
        public static final int expenseSavedMessage=0x7f04000a;
        public static final int expenseTagsText=0x7f040008;
        public static final int expenseTotalText=0x7f040007;
        public static final int expensesListAddItemTitle=0x7f04000d;
        public static final int expensesListButtonText=0x7f040002;
        public static final int expensesListEmpty=0x7f04000c;
        public static final int expensesListLabel=0x7f04000b;
        public static final int expensesListRemoveItemTitle=0x7f04000e;
        public static final int newExpenseButtonText=0x7f040001;
        public static final int valueText=0x7f040005;
    }
}
